# docker buildx bake --set "*.platform=linux/amd64" --load && docker-compose push
version: '2.4'
services:
  fakeservices.datajoint.io:
    build: .
    image: datajoint/nginx:v0.1.1
    ports:
      - "443:443"
