name: Docker Image CI

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu18.04
          - arch: aarch64
            distro: alpine_latest
          - arch: s390x
            distro: fedora_latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
      - name: Select environment
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
      - 
        name: Build Nginx Image
        run: | 
          docker build -t datajoint/nginx:${{ matrix.arch }} .
      -
        name: Login to Docker Hub
        if: |
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags') &&
          (
            github.repository_owner == 'datajoint' ||
            github.repository_owner == 'datajoint-company' ||
            github.repository_owner == 'dj-sciops'
          )
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Push Nginx Image
        if: |
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags') &&
          (
            github.repository_owner == 'datajoint' ||
            github.repository_owner == 'datajoint-company' ||
            github.repository_owner == 'dj-sciops'
          )
        run: docker-compose push
