name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest      
      
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Nginx Image
        run: docker buildx bake --set "*.platform=linux/amd64" --load
      -
        name: Push Nginx Image
        run: docker-compose push
        
        #uses: docker/build-push-action@v2
        #with:
          #context: frontend
          #file: Dockerfile
          #push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest
